### ISSUE TITLE
Move to Dracula organization

### ISSUE THREAD

**Issue by zenorocha** [dracula/tmux#1]
Hey @danerwilliams, would you like to move this repository to the Dracula organization?

You would continue to be the maintainer and everything else, but we would consider it an official theme and also add a page on draculatheme.com. 

Let me know what you think ;)

**Comment by danerwilliams** [comment]
Sure! I think that would be awesome! What would next steps look like?

**Comment by zenorocha** [comment]
I just sent you an invite to join the organization. Once you do that, you can transfer the repository.

After transferring, there are a couple of things we'll need for the site:
* Make sure you add a INSTALL.md file (https://github.com/dracula/template/blob/master/INSTALL.md)
* Change `screenshot.jpg`to `screenshot.png`
* Rename repo to `dracula/tmux`

Thanks!

**Comment by danerwilliams** [comment]
Done! Anything else I need to do?

**Comment by zenorocha** [comment]
It's now live! https://draculatheme.com/tmux 🎉 🎉 🎉
