### ISSUE TITLE
Enchancement: [Disable gray background]

### ISSUE THREAD

**Issue by coodyme** [dracula/tmux#101]
### Disable gray background
A way to disable gray background or choose terminal background color

**Comment by ethancedwards8** [comment]
> ### Disable gray background
> 
> A way to disable gray background or choose terminal background color

Sure. Feel free to send in a PR.

**Comment by 21st-centuryman** [comment]
I'm not sure how this would be implemented. Could it be possible to add a transparent background such as the one by powerlevel10k? Or would that mean we need to rewrite for this functionality to even be possible?

**Comment by ethancedwards8** [comment]
I'm not sure how other themes implement this, or how to implement it in the first place. Looking at other themes would probably be a good place to start.
