### ISSUE TITLE
Bug: conflict with tmux/resurrect?

### ISSUE THREAD

**Issue by ric-bianchi** [dracula/tmux#102]
### Describe the bug
It seems that since I have installed the dracula/tmux theme as plugin in the .tmux.config file, tmux/resurrect does not automatically save the sessions anymore. The manual save still works fine, but the automatic save seems broken.

Uninstalling dracula/tmux theme fixed the problem. 

Therefore, there might something that interferes with the auto-save of tmux/resurrect. 

Has anyone seen this already? Do you have a fix or a pointer to a possible solution?

### To Reproduce
1. Install dracula/tmux as plugin when tmux/resurrect is active. Restart tmux.
2. take a look at ~/.tmux/resurrect, to see whether the sessions are auto-saved
3. If not (as in my case), try to uninstall dracula/tmux; then restart tmux: in my case that fixes my problem.

### Expected behavior
resurrect timestamped sessions inside ~/.tmux/resurrect are not created anymore

### System
 - OS:   macOS 10.14.5 Mojave
- Tmux Version:  tmux 3.1b

**Comment by ethancedwards8** [comment]
I've never used resurrect, nor know anything about it. So I'm operating in the dark here, but this seems like something that's easy enough to fix. I'll take a look. 

Meanwhile, if you find the cause of the problem please post a solution.

**Comment by ric-bianchi** [comment]
Thanks a lot for your comment and help, @ethancedwards8 !  

Actually, `tmux-continuum` and `tmux-resurrect` plugins work together, so the interference could be with one of the two plugins.

I didn't find the cause yet; however, I probably have found a hint somehow: 

https://github.com/tmux-plugins/tmux-continuum/issues/22#issuecomment-375989238 

I don't fully understand that comment, because I don't know enough of the inner structure of the dracula tmux theme; but it could ring a bell for you, perhaps.

Just let me know if you need any additional piece of information from my side, of course.

Thanks again!

**Comment by ethancedwards8** [comment]
> Thanks a lot for your comment and help, @ethancedwards8 !
> 
> Actually, `tmux-continuum` and `tmux-resurrect` plugins work together, so the interference could be with one of the two plugins.
> 
> I didn't find the cause yet; however, I probably have found a hint somehow:
> 
> [tmux-plugins/tmux-continuum#22 (comment)](https://github.com/tmux-plugins/tmux-continuum/issues/22#issuecomment-375989238)
> 
> I don't fully understand that comment, because I don't know enough of the inner structure of the dracula tmux theme; but it could ring a bell for you, perhaps.
> 
> Just let me know if you need any additional piece of information from my side, of course.
> 
> Thanks again!

After looking at it, we set our own status, which is how the theme works. And that disables the hook that was mentioned in the issue that autosaves. 

I'm going to close for now, as this is just a symptom of the themes using the same method. I don't see a way around it.

**Comment by ric-bianchi** [comment]
Thanks for investigating this, @ethancedwards8, and for your kind help.

I'll try to investigate as well, to see if I'll find a workaround. In that case, I'll let you know here.

Thanks again, and I wish you a good day. Regards, -- Riccardo.
