### ISSUE TITLE
Bug: [this doesn't work]

### ISSUE THREAD

**Issue by kktt007** [dracula/tmux#115]
### Describe the bug
Only work when use this command
`set -g @dracula-plugins "battery network-bandwith time"` (but i can't find more plugin only these and cpu-usage etc)

how can i active the plugin because for others in https://draculatheme.com/tmux like`set -g @dracula-military-time true`, does not work.

### Screenshots
![](https://img.vim-cn.com/d7/895e74cf466f5431946e87ed0ccb5388e7e2de.png )
![](https://img.vim-cn.com/da/5e41fe0e9725d52e908a077fd73adb5d74faac.png)

### System
 - OS:  archlinux
- Tmux Version: latest

many thanks.

**Comment by o0th** [comment]
@kktt007 available plugins are listed in the [install](https://github.com/dracula/tmux/blob/master/INSTALL.md) file. The military time option show the time in the 24h format, seems correct to me.

**Comment by kktt007** [comment]
> @kktt007 available plugins are listed in the [install](https://github.com/dracula/tmux/blob/master/INSTALL.md) file. The military time option show the time in the 24h format, seems correct to me.

Many thanks.

it seems below does work for me.
# available plugins: battery, cpu-usage, gpu-usage, ram-usage, network, network-bandwith, weather, time

My issue is : set -g @dracula-military-time true etc.  this grammar desn not work for me. And i want more status i.e. (git)
below theme is cool. But i prefer dracula, because i use dracula everythere...
https://github.com/erikw/tmux-powerline/tree/master/segments

**Comment by o0th** [comment]
@kktt007 maybe you're expecting something different for `@dracula-military-time`
A git segment was working in progress from another user (#104), maybe I can give it a look to make it work. If you are interested in adding new functionalities you're free to open an issue/pr :)

**Comment by kktt007** [comment]
> @kktt007 maybe you're expecting something different for `@dracula-military-time`
> A git segment was working in progress from another user (#104). If you are interested in adding new functionalities you're free to open an issue/pr :)

Yes. Expecting something different for `@dracula-military-time`, but `set -g @dracula-...` this grammar does now work in  tmux.conf. It's ok now thanks. I also find https://draculatheme.com/tmux has changed. Soooooo clear.

For further  function and more  color. I think dracula/tumx will get better in the future.

Many thanks. I use Dracual on zsh, vim, tmux, anywhere.
