### ISSUE TITLE
Bug: [this doesn't work]

### ISSUE THREAD

**Issue by kktt007** [dracula/tmux#117]
### Describe the bug
I set  with `set -g @dracula-time-colors "gray white"`  I also tried with`green white` ... 
But the color seems the color is always `purple white', like below
And if i could change the color on left side.
Many thanks.
### Screenshots
![](https://img.vim-cn.com/05/a8bb2833dda25245064ae09910ffc3ef108931.png )

### System
 - OS: archlinux
- Tmux Version: latest

**Comment by o0th** [comment]
Yes this is an issue, there's already a PR ready: #114

**Comment by ethancedwards8** [comment]
@kktt007 why did you reopen this issue separately?

**Comment by ethancedwards8** [comment]
It's been merged.
