### ISSUE TITLE
Bug: [this doesn't work] Session text or smiley icon not center align

### ISSUE THREAD

**Issue by vpeopleonatank** [dracula/tmux#121]
### Describe the bug
@dracula-show-left-icon is set to any "session", "window", "smiley" or any character is not center align
### Expected behavior
character in left-icon position is center align
### Screenshots
![image](https://user-images.githubusercontent.com/30976876/131848467-ed276aca-8c24-4ab8-a5bf-7e32d01c2086.png)
![image](https://user-images.githubusercontent.com/30976876/131848943-af4fb427-5727-4ee4-9cbb-7db7f9c5353e.png)

### System
 - OS: Pop-os 20.04
- Tmux Version: tmux next-3.3

**Comment by ethancedwards8** [comment]
Yup, I see the issue.
```
  case $show_left_icon in
    smiley)
      left_icon="☺";;
    session)
      left_icon="#S";;
    window)
      left_icon="#W";;
    *)
      left_icon=$show_left_icon;;
  esac
```
It doesn't indicate the padding unlike other modules.
```
  padding=""
  if [ "$show_left_icon_padding" -gt "0" ]; then
    padding="$(printf '%*s' $show_left_icon_padding)"
  fi
  left_icon="$left_icon$padding"
```
Feel free to send in a PR, should be an easy enough fix.

**Comment by vpeopleonatank** [comment]
I use old dracula/tmux. Update to lastest tmux and `set -g @dracula-left-icon-padding 1` solve this issue.
