### ISSUE TITLE
Bug: Setting dracula-show-left-icon always defaults to "smiley"

### ISSUE THREAD

**Issue by mdi** [dracula/tmux#125]
### Describe the bug
If I `set -g @dracula-show-left-icon session` for example, the initial load of tmux always shows the smiley character. If I reload TPM, then the session number is shown.

### To Reproduce
1. Add `set -g @dracula-show-left-icon session` to tmux.conf
2. Start tmux.
3. Note the left status bar character is a smiley and not the session number.

### Expected behavior
The initial left status bar character should be what is set in tmux.conf.

### System
 - OS: Mac 11.6
- Tmux Version: 3.2a

**Comment by mdi** [comment]
This was due to misconfiguration on my part. Closing.

**Comment by ethancedwards8** [comment]
Thanks for closing. I was scratching my head trying to reproduce.
