### ISSUE TITLE
Bug: [Git plugin not working]

### ISSUE THREAD

**Issue by jkemp814** [dracula/tmux#134]
### Describe the bug
Git plugin would not show. Network bandwidth only shows 'Ethernet'. TEMP is not accurate. 40F degres off.

### To Reproduce
1. Go to 'Start Tmux session'
2. Click on 'Nothing to click on'
3. Scroll down to 'No scrolling needed'
4. See error: No error message

### Expected behavior
Expect to see check mark or exclamation mark for git repository. I have placed the two set -g @dracula-git-show lines in .tmux.conf and source the file. Still no git symbols. How do I get it to work?

### Screenshots
(screenshot below)

### System
 - OS: Ubuntu 21.04
 - Tmux Version: 3.1c-1
 - Gnome-terminal: 3.38.1-1
 - Zsh: 5.8-6
 - Oh-My-Zsh: Latest, no release number.

**Comment by jkemp814** [comment]
Gnome-terminal: 3.38.1-1
Zsh: 5.8-6
Tmux: 3.1c-1
Oh-My-Zsh: Latest, no release number.

![image](https://user-images.githubusercontent.com/12059343/136867190-130f70bf-cf57-4438-a6da-c6fa279414c3.png)

It's working now.

**Comment by ethancedwards8** [comment]
Please file separate issues for those issues.
