### ISSUE TITLE
Change smiley face to current session on left side of status bar

### ISSUE THREAD

**Issue by danerwilliams** [dracula/tmux#14]
Related to discussion with @smarquez1 in [Add ability to remove battery, weather, location and smiley face #12](https://github.com/dracula/tmux/issues/12).
  
Change the smiley face on the left side of the status bar to have 3 options:
* Current smiley face (changes color based on prefix activation)
* Nothing at all
* Current session name
  
I'm curious if people have other ideas for this side of the status bar as well!

**Comment by aquateen** [comment]
I would love to have the session name in the status bar 🙏

**Comment by Lulus792** [comment]
set -g @dracula-show-left-icon-session
