### ISSUE TITLE
Bug: colors are wrong

### ISSUE THREAD

**Issue by adrianmihalko** [dracula/tmux#142]
### Describe the bug

I would like to use Dracula theme for tmux, but for some reason I am getting different colors, than it should be. My terminal is iTerm2 with Night Owl theme on Mac and I am connecting to an Ubuntu server where tmux is running. I would expect, that tmux should overwrite iTerm2's theme, but this is not happening. Any idea why?

1. Main window + statusbar colors are wrong:
@ubuntu$ tmux
<img width="1275" alt="Screenshot 2021-12-03 at 22 12 01" src="https://user-images.githubusercontent.com/733361/144673602-ded846bf-6a74-43c3-852f-7daf3318a509.png">

2.  Main window colors are still bad, statusbar colors are good:
@ubuntu$ tmux -2
<img width="1280" alt="Screenshot 2021-12-03 at 22 20 01" src="https://user-images.githubusercontent.com/733361/144674220-8bebf5fd-3464-4984-a12d-7dade0e7953c.png">

My config is:
```
new-session
set-option -g mouse on
set-option -g status-right-length 200
setw -g automatic-rename on
set -s default-terminal 'xterm-256color'
set -g [@]plugin 'dracula/tmux'
run '~/.tmux/plugins/tpm/tpm'
```

### System
 - OS: Ubuntu 18.04
- Tmux Version: 3.3RC (also tried older versions)

**Comment by o0th** [comment]
tmux doesn't overwrite the main windows colors, it just output the status bar on the bottom. Not sure why you get those colors on the example 1. The example 2 is the normal behavior.

**Comment by adrianmihalko** [comment]
Thanks that makes sense so I installed Dracula theme to iTerm2. Now colors in main window are ok, but status bar is still only good when launched with "-2".

$tmu
<img width="1280" alt="Screenshot 2021-12-06 at 10 04 35" src="https://user-images.githubusercontent.com/733361/144818086-a840b5dc-dc14-43c9-aa07-04b62d8e5cf0.png">
x

$tmux -2
<img width="1280" alt="Screenshot 2021-12-06 at 10 04 35" src="https://user-images.githubusercontent.com/733361/144818117-6eee3acd-c3fb-4bf0-90bf-1263ac30f7dc.png">

As you can see terminals are the same (tmux-256color).

**Comment by o0th** [comment]
Can you try

```
tmux set-option -s default-terminal "screen-256color"
```

Or installing [tmux-sensible](https://github.com/tmux-plugins/tmux-sensible) and see if it works?

**Comment by adrianmihalko** [comment]
I tried, it's the same:

<img width="1181" alt="Screenshot 2021-12-09 at 01 27 31" src="https://user-images.githubusercontent.com/733361/145312476-cab05cf1-f75e-4f70-97b0-75918dead908.png">

Weird.

**Comment by adrianmihalko** [comment]
I found out that this happens only when I am using Mosh. I see some similar issues [here](https://github.com/mobile-shell/mosh/issues/599), but I can't find any workaround.

**Comment by ethancedwards8** [comment]
@adrianmihalko I see that you've closed this, has this been resolved?

**Comment by adrianmihalko** [comment]
@ethancedwards8 The first and most important: **$TERM outside tmux matters.**

...and the problem was that outside of tmux my default $TERM was set to xterm-color. I have also added AcceptEnv TERM to my sshd conf so $TERM is passed from the terminal I connecting with:

```
@MacBook-Pro:~/Downloads$ echo $TERM
xterm-256color
@MacBook-Pro:~/Downloads$ ssh ubuntu
Welcome to Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-163-generic x86_64)
madrian@ubuntu:~$ echo $TERM
xterm-256color
```

Now it works perfectly and I don't need to force tmux with -2.
