### ISSUE TITLE
[help] How can I remove smile at the left corner?

### ISSUE THREAD

**Issue by avatar-lavventura** [dracula/tmux#155]
Would it be possible to remove the smiley at the left corner?

When I do `set -g @dracula-show-left-icon session` instead it justs replace it with `0`.

**Comment by ethancedwards8** [comment]
How are you creating your tmux session?

**Comment by h-wata** [comment]
It was changed by the following settings in your `.tmux.conf`

```sh
set -g @dracula-show-left-icon session #smiley(default), session, window or *(as you like)
```

more details here:
https://github.com/dracula/tmux/blob/a966029b9938badd9ed945b634b917e574c0c322/scripts/dracula.sh#L42-L52

**Comment by avatar-lavventura** [comment]
I have tried: `set -g @dracula-show-left-icon session` but still green bar at the left corner `0` in it shows up:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/18537398/157628835-7c85e91b-ec8e-4d75-a44e-3a75202c50e1.png">

Is it possible to suppress `| 0 |` as well?

**Comment by h-wata** [comment]
You can remove it by changing the following part.

https://github.com/dracula/tmux/blob/a966029b9938badd9ed945b634b917e574c0c322/scripts/dracula.sh#L117-L123


change to:
```sh
tmux set-option -g status-left ""
````
![image](https://user-images.githubusercontent.com/20681658/157781852-13ae8ff0-a6f9-4c9f-9478-9b6328c36562.png)

**Comment by avatar-lavventura** [comment]
@h-wata Thank you
