### ISSUE TITLE
Rewrite weather module for international support 

### ISSUE THREAD

**Issue by danerwilliams** [dracula/tmux#16]
Rewrite the weather module to scrape a site which supports countries outside of US. 

Requirements:
* Continue using ipinfo.io for keyless api access to current location
* Scrape weather site (do not use an API key)
* Continue getting forecast to produce appropriate emoji
* Continue getting temperature (option of F or C)

Currently thinking the best site to scrape is wunderground.com because they have a simple url structure: wunderground.com/weather/region_code/city. It looks like in the US it takes region_code as the two letter code of your state. Otherwise, it seems to expect your country code.  

For example, Vancouver, British Columbia, Canada is:  
wunderground.com/weather/ca/vancouver  

whereas Seattle, Washington, United States is:  
wunderground.com/weather/us/wa/seattle  

I think this would work, the only challenge I see is that ipinfo.io doesn't seem to give region code, only the full region name and then the country code. However, currently I am getting the state/region code by scraping another website. Since it is only the US it might be worth just making a look up table to translate them.  
  
If anyone has any other thoughts on this let me know!

**Comment by danerwilliams** [comment]
I recently discovered [wttr.in](https://github.com/chubin/wttr.in) which I think would be the perfect api for this

**Comment by ethancedwards8** [comment]
I could take a crack at it.

**Comment by HugoLiconV** [comment]
> I recently discovered [wttr.in](https://github.com/chubin/wttr.in) which I think would be the perfect api for this

I was able to make it work using [wttr.in](https://github.com/chubin/wttr.in)

![Screenshot from 2020-07-04 17-55-49](https://user-images.githubusercontent.com/22970186/86522738-b816ff80-be1f-11ea-85fe-79087fc104a1.png)

**Comment by ethancedwards8** [comment]
Nice, beat me to it

**Comment by ethancedwards8** [comment]
You should submit a pull request

**Comment by danerwilliams** [comment]
Please submit a PR, also if you we should include the current location as well as the weather as it currently does.

**Comment by ethancedwards8** [comment]
#52
