### ISSUE TITLE
Loading via tmux.conf fails

### ISSUE THREAD

**Issue by mrgreen3** [dracula/tmux#170]
Added TPM to tmux and tried to load dracula theme as per guide, but after running Ctrl+b ... Shift I theme does not seem to load.

Is there any way to check if theme is loaded correctly?

**Comment by JannoTjarks** [comment]
Hi @mrgreen3, could you please provide us your .tmux.conf for a deeper look into your configuration. And maybe show us the content of your .tmux folder.

```
## List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

This should be a minimal .tmux.conf file.

**Comment by mrgreen3** [comment]
I have followed above and all seems to be working now... must have missing something when I first tried.

Have powerline bar now working just need to read up on getting it how I want it.

Thanks so much for your great project and help ;-)
