### ISSUE TITLE
Bug: [this doesn't work on ubuntu 22.04]

### ISSUE THREAD

**Issue by xahmad7** [dracula/tmux#172]
Hello
I'm using ubuntu 22.04 and cannot install it on tmux I followed the instructions
installed TPM, then Dracula Theme but nothing happend

**Comment by JannoTjarks** [comment]
Could you please provide your tmux.conf file?

**Comment by silentnights** [comment]
Same issue here. I have noticed some weird behavior after updating to Ubuntu 22.04, so I tried to uninstall and install the plugin, but it was not detected at all by tpm. !

I tried to uninstall other plugins and install them again and tpm does not have any issues with them.

**Comment by silentnights** [comment]
After upgrading to Ubutu 22.04, I noticed a weird behavior. It looks like my previous configuration is not respected.

I tried to uninstall and reinstall with tpm, but still. All my configurations are not respected. I tried to comment out my previous configuration and limit the configuration to few dracula plugins but still, it does not take any effect.

Here is my .tmux.conf

`set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "cpu-usage gpu-usage ram-usage"
#set -g @dracula-show-battery false
#set -g @dracula-show-network false
#set -g @dracula-show-location false
#set -g @dracula-show-left-icon session

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
`

**Comment by xahmad7** [comment]
The solution is to run this command after editing .tmuxconf
run from inside tmux
~/.tmux/plugins/tpm/bin/install_plugins

And then the theme will be installed

**Comment by silentnights** [comment]
The gray area in the lower bar issue seems to be resolved by itself at some point. Not sure, what caused it in the first place. I have a desktop and a laptop, both running Ubuntu 22.04. Both had the same issue. The desktop behaved normally a few days ago, potentially after some update/restart. I tried the same with the laptop, but for some reason `tpm` was refusing to load. So, I ended up just deleting my `.tmux.conf `and `.tmux` Dir from the laptop and getting them from the desktop, and it worked well again there as well.

**Comment by pataquets** [comment]
@xahmad7 Fancy to close the issue, if working? Let's keep the issue list tidy to make easier the maintainer's work.

**Comment by xahmad7** [comment]
Issue fixed thanks

**Comment by pataquets** [comment]
@xahmad7 Glad to know that.
Would you please close the issue, then? (Only the issue author or maintainers can)
Thanks!
