### ISSUE TITLE
'~/.tmux/plugins/tpm/tpm' returned 126

### ISSUE THREAD

**Issue by pentago** [dracula/tmux#178]
Upon adding this plugin without any configuration options, tmux throws following error:

'~/.tmux/plugins/tpm/tpm' returned 126

The error is gone after dracula plugin is disabled.

I'm using: MacOS 13 (Ventura) with tmux 3.3a on M1 Apple Silicon (arm64)

Anything else I could provide?

**Comment by pentago** [comment]
It is installed of course, not a newb :=

**Comment by ramaskez** [comment]
I also get the exact same result using Debian 11 (5.10.0-19-amd64) and tmux 3.1c. 

Again TPM is installed and the error is gone when I disable the plugin.

Please let me know if you need me to provide any further details.

**Comment by ramaskez** [comment]
After some digging if I fresh install Dracula:

edit ~/.tmux/plugins/tmux/scripts/dracula.sh and on line 175 add fi as the block:
```if [ $plugin = "spotify-tui" ]; then
      IFS=' ' read -r -a colors <<<$(get_tmux_option "@dracula-spotify-tui-colors" "green dark_gray")
      script="#($current_dir/spotify-tui.sh)"```

has no end fi.

chmod +x ~/.tmux/plugins/tmux/scripts/dracula.sh

and reload tmux all is working.

**Comment by bryan-hoang** [comment]
I've made #179 to implement @ramaskez's suggested fix, as it also worked for me.

**Comment by pentago** [comment]
Still having the same issue with this fix, not sure how it fixed it for you..

**Comment by pushkar96** [comment]
I wasted my complete day and was about to submit a PR when I saw someone just did.
Adding `fi` worked for me

The other thing you have to do is:
1. chmod +x dracula.sh
2. chmod +x dracula.tmux [This might not be needed]
