### ISSUE TITLE
Bug: Weather unit keeps resetting to Farenheit

### ISSUE THREAD

**Issue by jjant** [dracula/tmux#181]
### Describe the bug
My tmux config has the following relevant things for `dracula/tmux`:

```tmux
set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline true
set -g @dracula-show-fahrenheit false
```

When I reload (re-source) the tmux config, the temperature uses the correct Celsius unit, however after a while (maybe when it refetches the weather? Not sure), the unit resets to F.

### To Reproduce

1. Copy my config to your `tmux.conf`
2. Wait for a while (again, not totally sure what causes it)
3. Your temperature is in Fahrenheit again

### System
 - OS: macOS 12.6.1
- Tmux Version: `tmux 3.3a`

**Comment by danriedl** [comment]
Having the same issue. Even the fixed location resets to the IP location with this refresh.
```
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "git cpu-usage ram-usage weather time battery"
set -g @dracula-show-fahrenheit false
set -g @dracula-fixed-location "Buchhofen"
set -g @dracula-show-powerline true
set -g @dracula-military-time true
set -g @dracula-day-month true
```
