### ISSUE TITLE
Bug: spotify-tui size overflows

### ISSUE THREAD

**Issue by 21st-centuryman** [dracula/tmux#192]
Basically with songs that have longer names the size of the spotify-tui psuhes other plugins out of the view. See picture:
<img width="1499" alt="Screenshot 2023-02-12 at 20 59 01" src="https://user-images.githubusercontent.com/60197499/218334051-68527b32-9147-46b0-88cf-c314cac3bd01.png">

I think this shouldn't be too big of an issue. I will see if I have the time to fix a PR.

I have the latest version of tmux, and dracula/tmux if that helps

**Comment by 21st-centuryman** [comment]
<img width="1509" alt="Screenshot 2023-02-12 at 21 02 54" src="https://user-images.githubusercontent.com/60197499/218334249-017904f5-e5e0-40a9-9504-de8f7cf3b855.png">

Here is an extreme version of the issue.

**Comment by sydrawat01** [comment]
This happens with the kubernetes context as well, on the latest version of tmux and dracula/tmux.

**Comment by Theoreticallyhugo** [comment]
@21st-centuryman should be fixed now. use `set -g @dracula-spotify-tui-cutoff 30` to set 30 characters as an upper bound for spotify. (you can ofc also use any other value, but i like 30)
