### ISSUE TITLE
Bug: Missing Plugin on Documentation

### ISSUE THREAD

**Issue by danriedl** [dracula/tmux#193]
Not really a bug but I think the `kubernetes-context` plugin is missing on https://draculatheme.com/tmux.
<img width="857" alt="image" src="https://user-images.githubusercontent.com/107212962/218674223-428772d4-dd5f-43d6-9d06-7ae3579d7948.png">

Just found the (very cool) plugin by accident while checking the script folder.

**Comment by 21st-centuryman** [comment]
The spotify is also missing. I am not sure if you can send a PR to update the documentation

**Comment by danriedl** [comment]
>  ... I am not sure if you can send a PR to update the documentation

It seems that the documentation is not part of this repository. That's why I created the issue.

**Comment by ethancedwards8** [comment]
@danriedl and @21st-centuryman that information is updated by editing https://github.com/dracula/tmux/blob/master/INSTALL.md . If you wish to make any corrections, feel free to send in a PR. I've been gone for a bit so thinks are a bit unmaintained as of now but I hope to come back and get everything back in order!
