### ISSUE TITLE
Enhancement: display cwd as a right side tab item

### ISSUE THREAD

**Issue by jonathanforhan** [dracula/tmux#194]
### Describe the feature you'd like
I would like to know your thoughts on a new plugin called 'cwd' that prints the cwd as a tab item

### Describe risks you've considered
risks include:
- taking up precise tab space
- making it more necessary to have status-interval turned to 1 

### Describe alternatives you've considered
I've already written the implementation so the alternative is me just keeping my current setup, just wanted to know your thoughts on this feature I find useful.

![dracula-cwd](https://user-images.githubusercontent.com/99012095/222863330-4a020637-f91d-407a-bff4-c3af4efd2f9a.png)

gives path only for selected pane

![dracula-cwd-example](https://user-images.githubusercontent.com/99012095/222863382-9343ad7a-9c51-46f6-b205-88f18acb6aa9.png)

another example with longer path

**Comment by ethancedwards8** [comment]
I think it would be useful. However, why not just have it in your shell? I see that you're using vim as you use tmux, does the file path in the tmux bar automatically update as you change files in vim?

**Comment by jonathanforhan** [comment]
The main appeal for me is that I can now make my shell prompt something like:
- ```user@host:[fd]$```

and not
- ```user@host:[absolute/path/to/nested/fd]$```

while still seeing the absolute path in tmux

as for having it sync with your vim buffer, that was a good point so I implemented it, here is the example:

https://user-images.githubusercontent.com/99012095/230674436-67fbc6ee-ca60-4948-9663-59f65ef4f100.mp4

### Additions:
- 3 lines of vim autocmd for Buf callbacks (works on vim and neovim)
- ~/.vim/buf file that vim writes the current buffer to
- source the ~/.vim/buf file
- cwd.sh checks the vim_buf variable in buf file, if empty use tmux pane path else use vim buffer path

### Drawbacks:
- I believe you now have to have set focus-events on in tmux config
- extra file
- vim configuration

**Comment by ethancedwards8** [comment]
Interesting. That's cool. 

Think you could send a PR for the initial implementation (without the vim integration) with the appropriate documentation?
