### ISSUE TITLE
Bug: No bugfix release after 2.0.0 to package for Nix

### ISSUE THREAD

**Issue by alinanorakari** [dracula/tmux#197]
### Describe the bug
Release 2.0.0 from July 2021 is currently the latest release, but it contains bugs that were fixed in newer commits, like for example https://github.com/dracula/tmux/commit/8ea687e3274eb5ffc79e848d330fc91fd86af71a
I would like to update the NixOS package with a version that contains such bugfixes.

Please consider creating a bugfix release so that I can update the nixpkg definition.

### To Reproduce
See referenced version in the nixpkg: https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/misc/tmux-plugins/default.nix#L180
- Install the theme using the NixOS configuration or the Nix package manager
- Try changing the colors with `@dracula-time-colors`

### Expected behavior
colors of the time component to the far right change to the colors specified in `@dracula-time-colors`

**Comment by ethancedwards8** [comment]
Will do. Thanks for the reminder.

**Comment by ethancedwards8** [comment]
Here you go: https://github.com/dracula/tmux/releases/tag/v2.1.0

**Comment by alinanorakari** [comment]
Thank you, I'll submit an update to the NixOS package shortly
