### ISSUE TITLE
Bug: Weather Module not receiving anything

### ISSUE THREAD

**Issue by rackodo** [dracula/tmux#222]
### Describe the bug
Setting fixedLocation to *any* location returns Location Unavailable in the module.

### To Reproduce
Set dracula-fixed-location to any location.

### Expected behavior
The weather to appear.

### Screenshots
![Screenshot 2023-06-20 at 12 31 18 pm](https://github.com/dracula/tmux/assets/42397332/76962b7d-3c07-47f3-9e0f-0e4df9f7241c)

### System
 - OS: 14.0 Beta (23A5257q)
 - Tmux Version: 3.3a via Homebrew

**Comment by gambhirsharma** [comment]
@rackodo how did you fix it?
