### ISSUE TITLE
Enhancement: Use battery icon instead of label and status

### ISSUE THREAD

**Issue by Erimus-Koo** [dracula/tmux#225]
### Describe the feature you'd like
<img width="600" alt="image" src="https://github.com/dracula/tmux/assets/17139670/83961db1-1634-44c0-ace5-7acb7c2d3c81">

There are several battery icons available in the Nerd Font, which display both the percentage and charging status.
Mine is "JetBrainsMono Nerd Font".

<img width="1228" alt="image" src="https://github.com/dracula/tmux/assets/17139670/98fe683a-29c3-4a02-8767-46c85869af7f">

Using them instead of the heart label and "AC" will save space and increase clarity.

Of course not everyone installed the nerd font, so there might be an alternative option such as "use-battery-icon".

**Comment by ethancedwards8** [comment]
Good idea.

**Comment by sydrawat01** [comment]
> I'm wondering is there a possibility to update the icon based on the battery percentage, charging/not charging, etc?

<img width="1083" alt="image" src="https://github.com/dracula/tmux/assets/97932746/def262d6-7d6f-422f-ad86-423bd6c4b88d">


This config works well for me!
Of course, the only caveat is the user needs to have a Nerd Font installed.

**Comment by Erimus-Koo** [comment]
@sydrawat01 
I am not familiar with shell code, but this seems like a good attempt. 
Additionally, it would be nice to add color to indicate battery status - green for full charge, red for low battery - and establish some rules for when the device is charging.

**Comment by ethancedwards8** [comment]
Yeah this is something to think about but hard to implement without certain fonts. I like the idea of setting a custom battery prompt.

**Comment by Erimus-Koo** [comment]
I believe these glyphs should be included in all nerd fonts, but I'm not certain.
Nerd fonts look like some monospace fonts, append the icon glyphs(some standard subset), but maybe the subset has some different versions.
