### ISSUE TITLE
Bug: [status bar: sync-panes  doesn't work]

### ISSUE THREAD

**Issue by PengfeiM** [dracula/tmux#227]
### Describe the bug
I have configed  the sync-pane plugins, but there is no sync in my status bar

### Screenshots
![image](https://github.com/dracula/tmux/assets/45191163/79885b98-6ebd-49f9-93ba-f635d8ff9b39)

### System
 - OS: macOS 13.4.1 22F82 arm64
- Tmux Version: tmux: stable 3.3a (bottled), HEAD

**Comment by ethancedwards8** [comment]
Fixed by #228
