### ISSUE TITLE
Bug: Plugins using /dev/null not working correctly

### ISSUE THREAD

**Issue by rackodo** [dracula/tmux#229]
### Describe the bug
Plugins that redirect to /dev/null (network, weather) just don't work and always default to an "Unavailable" or "Offline" status.

### To Reproduce
1. Add either 'network' or 'weather' to the tmux plugins list in .tmux.conf.

### Expected behavior
The promised information.

### Screenshots
<img width="978" alt="Screenshot 2023-07-18 at 1 29 22 pm" src="https://github.com/dracula/tmux/assets/42397332/3b291aca-31fc-4a05-b2f8-817382fb0111">

### System
- OS: macOS Sonoma 14.0 (Beta)
- Tmux Version: 3.3a

**Comment by Theoreticallyhugo** [comment]
if this issue doesnt persist for you anymore, please consider closing.
i would propose closing this issue if there is no response within the next two weeks
