### ISSUE TITLE
Enhancement: Add a MPC/MPD Plugin

### ISSUE THREAD

**Issue by pspiagicw** [dracula/tmux#238]
### Describe the feature you'd like
A MPD plugin showing the currently playing song. MPD is a very popular offline music server (https://www.musicpd.org/)

The plugin would query the local MPD server through the command line tool `mpc`. Would be a good complement to the existing spotify-tui plugin. 

### User Options
Just like the `spotify-tui` plugin, there would be a option to configure the mpc client output. 

### Rough implementation. 
I already have a rough implementation that I use in my personal setup. It is a direct modification of the `spotify-tui` plugin. 
I am willing to open a PR to discuss the implementation further.

I have attached a screenshot of my personal implementation.

![image](https://github.com/dracula/tmux/assets/30765406/477f8436-0482-451e-b9fb-e5fb9759f196)

**Comment by JannoTjarks** [comment]
Hi,

I created the Spotify tui plugin :D 
Would be nice, if you push your code as git repo, because I am also using the mpd daemon. If you need help, just ask.

**Comment by pspiagicw** [comment]
Hi,

I have forked the repo and commited my changes (https://github.com/pspiagicw/tmux).
I have also opened a PR to merge my changes into the upstream repo.
