### ISSUE TITLE
Bug: Battery indicator showing AC even when unplugged

### ISSUE THREAD

**Issue by ethancedwards8** [dracula/tmux#25]
### Describe the bug
Battery indicator not working on laptop

### More details
When in tmux session, the battery status bar shows AC, like its plugged in, but it's actually not plugged in and should show the battery percentage.

### System
 - OS: Linux 5.4.28-gentoo-x86_64 (per `uame -sr`)
- Tmux Version: tmux 2.9a

**Comment by danerwilliams** [comment]
reopened because I noticed that the issue started occurring again

**Comment by ginglis13** [comment]
I think it might be a bash vs. zsh issue, now that mac uses zsh as default shell.

I ran this to test:

zsh:
```zsh
ginglis@smoke ~/projects/tmux git:(battery-bug)
➜ status=discharging
zsh: read-only variable: status
ginglis@smoke ~/projects/tmux git:(battery-bug)
➜ [[ "$status" = 'discharging' ]] && echo yeet

```

No output, whereas with bash:

```bash
ginglis@smoke ~/projects/tmux git:(battery-bug)
➜ bash
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ status=discharging
bash-3.2$ [[ "$status" = 'discharging' ]] && echo yeet
yeet
```

the conditional evaluates to true.

**Comment by danerwilliams** [comment]
@ginglis13 that makes sense to me although `battery.sh` uses a bash shebang so wouldn't it not matter what shell you are using? I'm also using bash rather than zsh on my mac.

**Comment by ginglis13** [comment]
I see, maybe the shell itself isn't the issue here then

**Comment by danerwilliams** [comment]
not really sure why this was the issue but double square brackets were added in at some point and that seemed to be causing the problem

**Comment by trietphm** [comment]
I'm using MacOS 10.15.7 and this command
https://github.com/dracula/tmux/blob/master/scripts/battery.sh#L70
return with a space character in the beginning, have to trim it to show the correct indicator. Not sure if it's a bug or what.

<img width="703" alt="image" src="https://user-images.githubusercontent.com/4161828/102017360-1b2a9c00-3d99-11eb-891a-02d83ac8c8b0.png">

**Comment by ethancedwards8** [comment]
> I'm using MacOS 10.15.7 and this command
> 
> ```shell
> 		Darwin)
> 			status=$(pmset -g batt | sed -n 2p | cut -d ';' -f 2)
> 		;;
> ```
> 
> https://github.com/dracula/tmux/blob/master/scripts/battery.sh#L70
> return "discharging" with a space character in the beginning, have to trim it to show the correct indicator. Not sure if it's a bug or what.
> 
> <img alt="image" width="703" src="https://user-images.githubusercontent.com/4161828/102017360-1b2a9c00-3d99-11eb-891a-02d83ac8c8b0.png">

Oh yeah, feel free to create a pull request to fix that. I think you could do it a better way than piping it into xargs 👍 @trietphm
