### ISSUE TITLE
Bug: [this doesn't work]

### ISSUE THREAD

**Issue by qrockz** [dracula/tmux#251]
### Describe the bug
![screenshot](https://github.com/dracula/tmux/assets/56853194/feae71c3-73ae-4f63-bfa3-eb16becac660)

I have uninstalled dracula. I have to mention that tpm  has never listed dracula as a plugin but it still worked somehow.

Now I've tried the cattpuccin plugin but I think dracula is still overwriting some settings. Look at the loaded modules (battery, wlan, weather). Theese modules were loaded in dracula before but since I've deinstalled it they are still loaded.

What should I do to completely remove dracula from tmux?

```
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'

# set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

set -g @plugin 'tmux-plugins/tmux-yank'

set -g status-position top

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator "  █"

set -g @catppuccin_window_default_fill "number"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#{pane_current_path}"

set -g @catppuccin_status_modules_right "application session date_time"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "yes"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "no"
run '~/.config/tmux/plugins/tpm/tpm'
```

**Comment by ethancedwards8** [comment]
Interesting. What are the contents of your `~/.tmux` and your `~/.config/tmux`?

**Comment by qrockz** [comment]
> Interesting. What are the contents of your `~/.tmux` and your `~/.config/tmux`?

~/.tmux I didn't use it

~/.config/tmux 
└─> ll
drwxrwxr-x t t 4.0 KB Wed Mar  6 07:05:55 2024  .
drwxrwxrwx t t 4.0 KB Sun Mar  3 10:09:20 2024  ..
drwxrwxr-x t t 4.0 KB Tue Mar  5 15:39:17 2024  layouts
drwxrwxr-x t t 4.0 KB Tue Mar  5 17:40:14 2024  plugins
.rw-rw-r-- t t 1.8 KB Tue Mar  5 19:37:45 2024  tmux.conf

I posted almost the same question at the cattpuccin repo and I've found out that dracula and cattpuccin use the same directory ../plugins/tmux
After deleting ../plugins/tmux and reinstalled cattpuccin and it works now.

Still confusing that tpm lists dracula or cattpuccin plugin as "tmux" (prefix + alt + U) . Should be renamed.
