### ISSUE TITLE
🐛 Bug: Documented flag set -g @dracula-show-fahrenheit false not working

### ISSUE THREAD

**Issue by cjones27** [dracula/tmux#252]
Hi! The documented flag `set -g @dracula-show-fahrenheit false` is not changing the temperature unit to Celsius
<img width="783" alt="Screenshot 2024-03-10 at 19 32 51" src="https://github.com/dracula/tmux/assets/48262167/b93ea3bf-bf41-4a05-8860-3f88d46fbca0">

**Comment by ethancedwards8** [comment]
Hi there! Could you paste the contents of your `.tmux.conf`?

**Comment by cjones27** [comment]
Hi! Thanks for the quick response! I'm not really sure what happened, but after reopening tmux the next day the it had change to Celsius. Maybe it bugged because I changed the other parameters with no problems except the temperature unit, or maybe it had to poll the temperature again (?)

Thanks @ethancedwards8!

**Comment by ethancedwards8** [comment]
I think you are probably right. It could also be that your tmux configuration did not refresh when you made the change, that happens sometimes. Thanks for the issue.
