### ISSUE TITLE
Bug: `network` module doesn't work on macOS 14.4 and later

### ISSUE THREAD

**Issue by pratnala** [dracula/tmux#256]
### Describe the bug
The `airport` command has been deprecated on macOS 14.4. This leads to the `network` module not working as intended.

### To Reproduce
1. Enable network plugin in `tmux.conf` - `set -g @dracula-plugins network`
2. Reload tmux
3. See bottom right to see network name
4. Nothing is shown

### Expected behavior
Network name, if wireless, or Ethernet otherwise, must be shown instead of a blank space.

### Screenshots

<img width="162" alt="Screenshot 2024-04-01 at 10 28 54 AM" src="https://github.com/dracula/tmux/assets/1689565/5b450623-d0d4-454b-b17d-740b5aa108b9">

Network name must show in the blue box but is blank.

### System
 - OS: macOS 14.4.1
- Tmux Version: 3.2a

**Comment by amitizle** [comment]
This is the alternative to `airport`;
```bash
networksetup -getairportnetwork en0 | cut -d ':' -f2 | sed 's/^[[:blank:]]*//g'
```

**Comment by pratnala** [comment]
Checked in #259 thanks to @amitizle's suggestion

**Comment by pratnala** [comment]
@amitizle This command now doesn't work on macOS 15. Sigh, Apple.

**Comment by amitizle** [comment]
@pratnala on every major version update there's some sort of backwards compatibility issue 😵

**Comment by pratnala** [comment]
@amitizle Know any other way to get network name? Not finding a simple enough way.

**Comment by Theoreticallyhugo** [comment]
fixes to that are currently being discussed in #291
