### ISSUE TITLE
I want to hide the location or remove the location from powerline

### ISSUE THREAD

**Issue by GUNGODD** [dracula/tmux#262]
![image](https://github.com/dracula/tmux/assets/104669514/12e024ee-0c2e-4fa7-a29a-5db81568bbe1)

**Comment by hpk992** [comment]
you should be able to hide it with `set -g @dracula-show-location false`

**Comment by Theoreticallyhugo** [comment]
maybe we should close this issue due to inactivity?

**Comment by gamerson** [comment]
> you should be able to hide it with `set -g @dracula-show-location false`
This doesn't seem work with latest dracula/tmux. 🤔

**Comment by GUNGODD** [comment]
@gamerson  i changed my tmux config  :smiling_face_with_tear:
