### ISSUE TITLE
WSL/Debian - Weather - Location Unavailable

### ISSUE THREAD

**Issue by Erich-Chen** [dracula/tmux#271]
### Describe the bug
The weather module displays "Location Unavailable" on WSL/Debian platform.

### Cause
`ping `does not work on WSL/Debian. Thus `ping -q -c 1 -W 1 ipinfo.io` fails.

Seeing Line 66 - 70 in https://github.com/dracula/tmux/blob/master/scripts/weather.sh, "Location Unavailable" displays.

### Resolution
Referring to [Issue #5109](https://github.com/microsoft/WSL/issues/5109) for WSL, a workaround can be:

`$ sudo setcap cap_net_raw+p /bin/ping`

### System
 - OS: Debian 12 on WSL (Windows Subsystem Linux)
- Tmux Version: 3.3a

**Comment by ethancedwards8** [comment]
Check now? We reworked the plugin a little bit to use a builtin TCP connection.

**Comment by guimochila** [comment]
@ethancedwards8 `timeout` command is not available on OSX bash version by default.  To make it work locally I had to add a timeout command in the `weather.sh` file:

```sh
timeout() {
    if [ $# -lt 2 ]; then
        echo "Usage: timeout SECONDS COMMAND [ARG]..."
        return 1
    fi

    local duration=$1
    shift
    perl -e 'alarm shift; exec @ARGV' "$duration" "$@"
}
```

If I execute `/bin/bash` and try to execute the `timeout` function I get a command not found error. I'd have to install coreutils package to have access to the timeout command.

**Comment by ethancedwards8** [comment]
> @ethancedwards8 `timeout` command is not available on OSX bash version by default. To make it work locally I had to create a timeout command in the `weather.sh` file:
> 
> ```shell
> timeout() {
>     perl -e 'alarm shift; exec @ARGV' "$duration" "$@"
> }
> ```
> 
> I'd have to install coreutils package to have access to the timeout command but this is already adding dependency to a bash script.

I had not considered that. If you would like to submit a PR to fix that, I will accept it.

**Comment by guimochila** [comment]
@ethancedwards8 sure! I can open a PR to fix it. xD

**Comment by guimochila** [comment]
@ethancedwards8 PR is open: https://github.com/dracula/tmux/pull/288
