### ISSUE TITLE
Enhancement: also show NVIDIA gpu usage in laptops

### ISSUE THREAD

**Issue by osbm** [dracula/tmux#272]
Most laptops have NVIDIA gpus as discreet GPUs in addition to the iGPU of the processor. Because of this, `lspci | grep VGA` will only show iGPU. And nvidia card is shown as '3D Controller'. Here is my output:
```
$ lspci | grep -iP 'VGA|3D'
00:02.0 VGA compatible controller: Intel Corporation Iris Plus Graphics G7 (rev 07)
06:00.0 3D controller: NVIDIA Corporation GP108M [GeForce MX250] (rev a1)
```

In the scripts gpu type is determined by `lspci` command and statistics is obtained by `nvidia-smi` command. I can run the `nvidia-smi` commands with success. But because of the lspci command it shows `GPU unknown`.

Can we update this functionality?

**Comment by Theoreticallyhugo** [comment]
hey @osbm,
setting `set -g @dracula-ignore-lspci true` should now allow you to always see your NVIDIA gpu.
please let us know if this fixes your issue or if it can be closed :D

**Comment by osbm** [comment]
Wow, thank you so much! Now the same configuration works on both laptop and desktop (both have nvidia but desktop doesnt have iGPU).

Awesome. We can close this now.
