### ISSUE TITLE
Square artifacts appearing between section in the tmux line

### ISSUE THREAD

**Issue by rtaibah** [dracula/tmux#28]
### Describe the bug
Square artifacts appearing beside the smiley face, the battery, and date.

### Screenshots
![Screen Shot 2020-05-22 at 6 56 36 AM](https://user-images.githubusercontent.com/707668/82629887-b7bcff00-9bf9-11ea-8139-ef39a73bd2bb.png)

### System
 - OS: Mac OSX
- Tmux Version: 3.1b

**Comment by ethancedwards8** [comment]
What terminal are you using? Some terminals won't support the theme. Like ST, from suckless has a hard time with powerline.

**Comment by danerwilliams** [comment]
did you try to enable powerline? It appears that you don't have powerline installed.

either install powerline font, or just make sure that powerline is disabled which it should be disabled by default

**Comment by rtaibah** [comment]
@ethancedwards8 I am using Hyper.

@danerwilliams No I haven't. I have airline.

**Comment by danerwilliams** [comment]
do you have `set -g @dracula-show-powerline true` in your .tmux.conf? Otherwise you shouldn't be getting that

**Comment by rtaibah** [comment]
Yes! That was the problem.

Embarrassing.

**Comment by danerwilliams** [comment]
no problem :)
