### ISSUE TITLE
Bug: [You are not associated with an AirPort network.]

### ISSUE THREAD

**Issue by jby** [dracula/tmux#290]
### Describe the bug
Probably not a bug with dracula.

In macOS 15 Sequoia, `networksetup -getairportnetwork [device]` no longer replies with the actual network...
It just says: `You are not associated with an AirPort network.`

### System
 - OS: macOS 15 Sequoia
- Tmux Version: doesn't matter...

**Comment by haroldduan** [comment]
My laptop system version is **macOS Sequoia 15.0.1**, I modified the content of the `network.sh` script file, temporarily cope with it ... 🤐
![WechatIMG2593](https://github.com/user-attachments/assets/f860b31c-7ffe-4dcf-b06c-c7a866f7b340)
