### ISSUE TITLE
Enhancement: Make status bar modules / color more configurable

### ISSUE THREAD

**Issue by danerwilliams** [dracula/tmux#42]
### Describe the feature you'd like

Instead of just having enable / disable for the various modules (cpu, weather, battery, etc.) have a configuration option which accepts a list specifying the desired modules in the desired order for them to appear. There should also be a configuration option which specifies the corresponding dracula colors for these modules. 

### Describe risks you've considered

The user may not set this configuration option

### Describe alternatives you've considered

If not specified, default to make dracula theme look like it does in the screenshot

**Comment by ethancedwards8** [comment]
I have an idea for how we would implement it. When we have the user specify the order of the modules in the .tmux.conf, we can store it as an array, then loop through it and display it that way. For the colors we will do the same thing. Just an idea.

**Comment by danerwilliams** [comment]
Yes I may have been unclear about this but that’s is what I meant by accepting a list as a configuration options.
