### ISSUE TITLE
Enhancement: Add panel zoom indication in status bar

### ISSUE THREAD

**Issue by ddiegosr** [dracula/tmux#47]
### Describe the feature you'd like
Add an indication in the status bar when a window has zoomed panels.

**Comment by ugirc** [comment]
You can add these two lines after `run '~/.tmux/plugins/tpm/tpm'`
```
setw -g window-status-current-style "bg=#5F5FAF" 
setw -g window-status-current-format '#{?window_zoomed_flag,#[fg=#d6FF03],} #I #W ' 
```
![image](https://user-images.githubusercontent.com/46078304/95047316-6df03380-0718-11eb-8140-8da3e78d64b2.png)

**Comment by spoulson** [comment]
After some research, I came up with a solution.  Proposal PR:

https://github.com/dracula/tmux/pull/75

**Comment by tkolleh** [comment]
No change after adding the above lines to the bottom of `.tmux.conf` file, reloading the environment, killing the server and finally opening tmux with zoomed in pane.

**Comment by spoulson** [comment]
@ethancedwards8 With https://github.com/dracula/tmux/pull/75 merged, this issue can be closed as resolved.

**Comment by ethancedwards8** [comment]
Yup, not sure why it didn't close automatically, probably just didn't mention the issue or something. Thanks.
