### ISSUE TITLE
weather doesn't work

### ISSUE THREAD

**Issue by TyNguyen2001** [dracula/tmux#51]
I live in Vietnam. Does the weather only work with the US?
Thanks for the help!
### Screenshots
![Screenshot from 2020-07-04 00-50-55](https://user-images.githubusercontent.com/64082226/86490268-fca78a00-bd90-11ea-9844-1263434d46e6.jpg)
### System
 - OS: Ubuntu 20.4
- Tmux Version: 3.0a

**Comment by danerwilliams** [comment]
Only works in US at the moment #16
