### ISSUE TITLE
Bug: ram_info reports negative memory use on Darwin

### ISSUE THREAD

**Issue by ReagentX** [dracula/tmux#53]
This line:

https://github.com/dracula/tmux/blob/60c2017fb05479eea782d49e68143f181ff2b8da/scripts/ram_info.sh#L21

```bash
❯ top -l 1 -s 0 | grep PhysMem | sed 's/[a-z]//g; s/[A-Z]//g; s/[()]//g' | awk '{printf "%d\n", $2-$3-$5}'
-3442
```

### Describe the bug
Memory shows as negative instead of positive

### To Reproduce
1. Add `set -g @dracula-ram-usage true` to `.tmux.conf`

### Expected behavior
Used memory shows correctly

### Screenshots
![image](https://user-images.githubusercontent.com/1920666/88199534-faf41800-cc12-11ea-9530-ae7fcdc89af5.png)

### System
 - OS: MacOS 10.14.6 (18G6020)
- Tmux Version: tmux 3.1b (installed via`brew`)

**Comment by ReagentX** [comment]
I do not quite understand what the problem here is:

❯ top -l 1 -s 0 | grep PhysMem
PhysMem: 16G used (3127M wired), 171M unused.
❯ top -l 1 -s 0 | grep PhysMem | sed 's/[a-z]//g; s/[A-Z]//g; s/[()]//g'
: 16  3129 , 160 .
❯ top -l 1 -s 0 | grep PhysMem | sed 's/[a-z]//g; s/[A-Z]//g; s/[()]//g' | awk '{printf "%d\n", $2-$3-$5}'
-3274

**Comment by danerwilliams** [comment]
@ethancedwards8 do you have any thoughts?

**Comment by ethancedwards8** [comment]
Hmm, this is certainly odd. I'll look into it. 

How it worked (or at least I though) top would output memory, and then I just used sed to get rid of all the other stuff. Then used awk to do the correct math (from stackoverflow).

@ReagentX Whats the output of just `top -l 1 -s 0 | grep Physmem`? @danerwilliams do you use this? Have you ever saw something like this?

**Comment by ReagentX** [comment]
I logged each piece of that bash command in my comment above.

**Comment by ethancedwards8** [comment]
Oh yeah, sorry missed that

**Comment by ethancedwards8** [comment]
https://askubuntu.com/questions/791270/why-are-memory-statistics-in-top-and-htop-different

That's what I tried to do with awk to get the true memory

**Comment by ReagentX** [comment]
I think, given the formula in that post, you want this:

```bash
top -l 1 -s 0 | grep MemRegion | sed 's/[a-z]//g; s/[A-Z]//g; s/[()]//g' | awk '{printf "%d\n", $4+$6+$8}'
```

The one in the repo takes the 16 from the total memory, subtracts wired memory, and subtracts unused. This one adds the resident, private, and shared regions in MiB, which comes closer to, but not exactly, what `htop` shows. Here is a breakdown:


```bash
❯  top -l 1 -s 0 | grep MemRegion
MemRegions: 98579 total, 3900M resident, 155M private, 2462M shared.
~
❯ top -l 1 -s 0 | grep MemRegion | sed 's/[a-z]//g; s/[A-Z]//g; s/[()]//g'
: 98633 , 3900 , 155 , 2461 .
~
❯ top -l 1 -s 0 | grep MemRegion | sed 's/[a-z]//g; s/[A-Z]//g; s/[()]//g' | awk '{printf "%d\n", $4+$6+$8}
6505
```

For me, `top -l 1` looks like this:

```log
Load Avg: 2.27, 2.48, 2.54
CPU usage: 3.79% user, 10.12% sys, 86.7% idle
SharedLibs: 347M resident, 84M data, 31M linkedit.
MemRegions: 98407 total, 3890M resident, 153M private, 2459M shared.
PhysMem: 16G used (2568M wired), 355M unused.
VM: 3030G vsize, 1993M framework vsize, 189787(0) swapins, 246738(0) swapouts.
Networks: packets: 11305616/14G in, 4130507/606M out.
Disks: 6066408/98G read, 3462599/50G written.
```

**Comment by ethancedwards8** [comment]
Okay, yeah, that looks good. If you want to submit a PR to fix it that'd be great. I don't have a Mac so I borrowed one to test everything on, if you find any issues with anything else let me know and I'll try to be of use.

**Comment by ReagentX** [comment]
Sure, I am looking into a more reliable way to get memory usage; I will make a PR when I land on a solution.

**Comment by ReagentX** [comment]
Looks like `htop` adds together active and wired memory to get this value:

https://github.com/hishamhm/htop/blob/402e46bb82964366746b86d77eb5afa69c279539/darwin/Platform.c#L229

We can acquire the sum by using:

```bash
❯  vm_stat | grep ' active\|wired ' | sed 's/[^0-9]//g' | head -n 8 | paste -sd+ - | bc
2047931
```

From here, we multiply by the page size of `4096` to get the total bytes and divide by `1073741824` to get the number of GiB or `1048576` to get the number of MiB.

**Comment by ethancedwards8** [comment]
Yeah, that looks great! One thought though, could we use awk instead of bc? I'm not sure if `bc` comes installed by default, if it does then no worries. We won't to limit to reliance on external programs as much as possible. The reason I ask is because on Linux you usually have to install.

**Comment by ReagentX** [comment]
Good point, I think it is included on MacOS but I will double check before submitting an MR.

**Comment by ReagentX** [comment]
I can't seem to find a source on whether `bc` is pre-installed, so I will use this to get the number of bytes:

```bash
vm_stat | grep ' active\|wired ' | sed 's/[^0-9]//g' | paste -sd ' ' -  | awk '{printf "%d\n", ($1+$2) * 4096}
```

Then I will use the existing conditional to determine whether to format in MB or GB.

**Comment by ethancedwards8** [comment]
Very nice, everything looks good!
