### ISSUE TITLE
Status bar not showing CPU/GPU usage

### ISSUE THREAD

**Issue by backpropper** [dracula/tmux#61]
It seems like now the status bar does not show any of the CPU/GPU percentage? Did anything change?

_Originally posted by @backpropper in https://github.com/dracula/tmux/pull/50#issuecomment-671603599_

**Comment by ethancedwards8** [comment]
It's working for me, maybe share your .tmux.conf file?

**Comment by backpropper** [comment]
the related lines that are in my `.tmux.conf` are: 
```
set -g @dracula-show-weather false
set -g @dracula-show-network false
set -g @dracula-show-battery false
set -g @dracula-show-powerline true
set -g @dracula-border-contrast true
set -g @dracula-cpu-percent true
set -g @plugin 'dracula/tmux'
```

**Comment by ethancedwards8** [comment]
For the cpu usage, its supposed to be `set -g @dracula-cpu-usage true` and it seems you haven't enable gpu. More info here https://github.com/dracula/tmux/blob/master/INSTALL.md#configuration

**Comment by backpropper** [comment]
Oh I see. Thanks! It looks like this still requires the user to open the tmux session on the machine that has the GPU. Also what happens if there are multiple GPUs loaded on the machine?

**Comment by backpropper** [comment]
Also how do I set the update interval? My status bar seems to be displaying the same numbers since the beginning.

**Comment by ethancedwards8** [comment]
I've submitted a PR to fix that, it should be by default 10 seconds for gpu ram and cpu and 5 for everything else.

Also make sure you have the most up to date version, you can update by hitting *prefix* + U (shift + u) and then typing all

**Comment by danerwilliams** [comment]
@ethancedwards8 Can you link this issue to the PR

**Comment by ethancedwards8** [comment]
#60

**Comment by ethancedwards8** [comment]
@danerwilliams I think I did that right

**Comment by ethancedwards8** [comment]
@backpropper you can now set the refresh rate interval. https://github.com/dracula/tmux/blob/master/INSTALL.md

**Comment by backpropper** [comment]
Thanks @ethancedwards8! Is there an update on this:
Oh I see. Thanks! It looks like this still requires the user to open the tmux session on the machine that has the GPU. Also what happens if there are multiple GPUs loaded on the machine?

**Comment by ethancedwards8** [comment]
On 20/09/12 11:52PM, Abhinav Gupta wrote:
> Thanks @ethancedwards8! Is there an update on this:
> Oh I see. Thanks! It looks like this still requires the user to open the tmux session on the machine that has the GPU. Also what happens if there are multiple GPUs loaded on the machine?
If there are multiple GPU's it should be average out the percentages.
There was a PR merged a while ago https://github.com/dracula/tmux/pull/58 that put this into effect.

**Comment by backpropper** [comment]
Great thanks!

**Comment by ethancedwards8** [comment]
On 20/09/13 12:04AM, Abhinav Gupta wrote:
> Great thanks!
Yep, let me know how it goes!

**Comment by ethancedwards8** [comment]
Closing since this is stale. Reopen if needed.

**Comment by nylar357** [comment]
I had to do a little editing to line 21 of scripts/gpu_usage.sh

`lspci | grep NVIDIA | head -n 1 | awk '{print $5}'`

removing the verbosity call and grepping NVIDIA rather than VGA.  On a Dell 5970 with a GTX 1060
