### ISSUE TITLE
Bug: git pull failed due to weather.txt chnages

### ISSUE THREAD

**Issue by zethra** [dracula/tmux#70]
### Describe the bug
The sleep_weather script writes to weather.txt which is tracked by git.  This file being changed means that git pulls fail due to upstaged changes (at least on my system, I have the default pull stagey as rebase).  Either way, have the script write to a checked in file isn't a good idea.

### To Reproduce
1. Run tmux with with the weather plugin enabled
    1.5 (might be needed) Set the repo or global config to rebase on pull instead of merge
2. Try to run git pull on the plugin

### Expected behavior
The plugin shouldn't write to checked in files.

### System
 - OS: Linux (Manjaro)
- Tmux Version: 3.1b

**Comment by zethra** [comment]
I submitted a patch to fix this https://github.com/dracula/tmux/issues/70

**Comment by ethancedwards8** [comment]
Closed by #71
