### ISSUE TITLE
Enhancement: Can I use 24-hour clock instead of 12-hour clock with prefix + t

### ISSUE THREAD

**Issue by ugirc** [dracula/tmux#74]
### Describe the feature you'd like
When I press `prefix + t`, it shows `6:23 PM`. Is it possible to use the tmux default format `18:23`?

![image](https://user-images.githubusercontent.com/46078304/95068497-f29e7a00-0737-11eb-8b67-87ab9ec9ad69.png)

**Comment by ethancedwards8** [comment]
Good question, this is probably possible but I'm not sure how to go about it best. Definitely would like to see this though. Thanks for the issue. If I have the time I'll try to create a solution :+1:

**Comment by ethancedwards8** [comment]
Actually, I've just found a solution! I'll make a commit and update as soon as I can!

**Comment by ethancedwards8** [comment]
Got it working :)

**Comment by ugirc** [comment]
> Got it working :)

Thanks for your work👏.So now do I need to reinstall the tmux dracula plugin to use 24-hour, or just modify my old dracula.sh as your commit did?

It would be better if this solution can be introduced in the README.md.

**Comment by ethancedwards8** [comment]
If you're using tpm you can press `prefix + U` and type all, and it'll update all your plugins. But you need to have military time enabled in your .tmux.conf, you can find instructions on how to do that here: https://draculatheme.com/tmux

**Comment by ugirc** [comment]
> If you're using tpm you can press `prefix + U` and type all, and it'll update all your plugins. But you need to have military time enabled in your .tmux.conf, you can find instructions on how to do that here: https://draculatheme.com/tmux

It works now, thank you!

**Comment by ethancedwards8** [comment]
Yup! Thanks for the issue.

**Comment by ugirc** [comment]
> Yup! Thanks for the issue.

BTW, is is possible to show the clock with the format `hh:mm:ss` when `prefix + t`? 

I saw this kind of style in other people's tmux.

---

Maybe... this would be an unimportant requirement ...

**Comment by ethancedwards8** [comment]
Possibly, I'll check it out when I get home from school.

**Comment by ethancedwards8** [comment]
Also, is there any practical use for this? Not to seem rude but I'm genuinely curious how it's helpful except for rices.

**Comment by ugirc** [comment]
> Also, is there any practical use for this? Not to seem rude but I'm genuinely curious how it's helpful except for rices.

Not too much practical use.
In a way, just let me remember that the time is flying :joy:

**Comment by OnkarRuikar** [comment]
> BTW, is is possible to show the clock with the format `hh:mm:ss` when `prefix + t`?

Looks like it's not made configurable in tmux: https://github.com/tmux/tmux/blob/master/window-clock.c#L227-L233

Update the patterns and [re-build](https://github.com/tmux/tmux#from-version-control) the tmux:
```diff
-strftime(tim, sizeof tim, "%l:%M ", localtime(&t)); 
+strftime(tim, sizeof tim, "%l:%M:%S ", localtime(&t)); 
```
