### ISSUE TITLE
Enhancement: Rename git repo to "dracula-tmux" to avoid creating nondescript "tmux" plugin dir

### ISSUE THREAD

**Issue by spoulson** [dracula/tmux#76]
### Describe the feature you'd like
Because the repo is currently named "dracula/tmux", installing the plugin creates a "tmux" plugin directory.  This fails to identify itself as dracula related when listing plugins:
![image](https://user-images.githubusercontent.com/102494/95102529-7db04d80-0701-11eb-9444-efde98a48e11.png)

An easy fix is to rename the repo to "dracula/dracula-tmux".  The plugin directory will then be "dracula-tmux".

### Describe risks you've considered
The upgrade path for existing users may not be impacted.  After renaming a repo, the original repo path is still accessible and redirects to the new name.   Existing users will continue to function when running tpm update (prefix + U).

See: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/renaming-a-repository

### Describe alternatives you've considered
N/A

**Comment by ethancedwards8** [comment]
Sorry I don't believe this would be possible. It breaks the naming convention the whole organization follows, I think being the outlier would be a bad look.

**Comment by ethancedwards8** [comment]
Also, I don't really see how this an issue unless there's a conflict with another plugin?

**Comment by spoulson** [comment]
@ethancedwards8, it certainly could conflict with another plugin.  Although, at this time I have not found one.  Seems inevitable.

Maybe tpm lets you checkout a plugin to a different directory name?  I haven't found if that's possible.

Your call.  It seems awkward when I first realized.

**Comment by ethancedwards8** [comment]
I don't know. Probably so. Look into it, but we probably won't be renaming the repo.
