### ISSUE TITLE
Bug: [RAM status bar doesn't show the how many GB used]

### ISSUE THREAD

**Issue by ugirc** [dracula/tmux#77]
### Describe the bug
I use `set -g @dracula-ram-usage true`

But it shows like this:
![image](https://user-images.githubusercontent.com/46078304/96098730-09498b80-0f05-11eb-81e5-20ce29b1661e.png)

It doesn't show like `5GB/16GB`

How can I solve it?

**Comment by ethancedwards8** [comment]
We need some more info, what operating system are you using? Are you using tpm? Are you using the most up to date theme and tmux version?

**Comment by ugirc** [comment]
> We need some more info, what operating system are you using? Are you using tpm? Are you using the most up to date theme and tmux version?

My OS is `Ubuntu 20.04.1 LTS x86_64`. My tmux version is `tmux 3.0a`

And I am using tpm. Also I have use the `prefix + U` to update the tmux.

```
set -g @plugin 'dracula/tmux' 
# Configuration
set -g @dracula-show-weather false
set -g @dracula-show-battery false
# set -g @dracula-show-fahrenheit false 
# set -g @dracula-show-timezone true # CST
set -g @dracula-show-left-icon session 
set -g @dracula-refresh-rate 4 
set -g @dracula-cpu-usage true
set -g @dracula-ram-usage true
# set -g @dracula-gpu-usage true
# set -g @dracula-day-month true
# set -g @dracula-border-contrast true
set -g @dracula-military-time true 

# === theme dracula end ===
# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

Update
After my try, it works.

I found maybe it is because I use an ubuntu with the chinese mode.
So the free -g shows like this
![image](https://user-images.githubusercontent.com/46078304/96205103-680c1500-0f98-11eb-9511-f8b886c330f7.png)

But in `ram_info.sh` it use `Mem` to locate the column to $2

![image](https://user-images.githubusercontent.com/46078304/96205249-adc8dd80-0f98-11eb-9de6-890875ec7db7.png)


So after I change the `Mem` into 内存，it works！

![image](https://user-images.githubusercontent.com/46078304/96205731-e6b58200-0f99-11eb-931c-dea3083150b4.png)


Maybe the only disadvantage of this solution is I can't follow this project's update in the future.

**Comment by ethancedwards8** [comment]
I see the issue, you have a different LOCALE, so yes. It is because you have the Chinese mode. I don't have this issue on my end because my LOCALE is en_US.UTF-8.

Try adding `export LC_ALL="en_US.UTF-8"` to the top of the ram_info file and undoing any changed you've made.

**Comment by ethancedwards8** [comment]
Just pushed a commit: ca2632845390c2bc40d578d4e94758cc9ce4889e

Try it now after updating, I think it should fix the issue.

**Comment by ethancedwards8** [comment]
Closing because no response.
