### ISSUE TITLE
Bug: Weather uses incorrect unit

### ISSUE THREAD

**Issue by evert** [dracula/tmux#87]
### Describe the bug

I don't think switching to celcius works!

I tried the following:

    set -g @dracula-show-fahrenheit false

in `.tmux.conf`, but it doesn't appear to have an effect.

P.S.: config is hilariously American. Fahrenheit by default, month/day in reverse order and calls 24h clock 'military' time. Great theme though =)

**Comment by ethancedwards8** [comment]
> P.S.: config is hilariously American. Fahrenheit by default, month/day in reverse order and calls 24h clock 'military' time. Great theme though =)
To be fair, the two main developers are American ;)

To the actual bug, we rewrote the temperature script a few PR's ago, I bet we forgot to mess with the Celsius option. I'll take a look!

**Comment by evert** [comment]
Awesome =)

**Comment by TimDaub** [comment]
<img width="200" alt="Screen Shot 2021-01-20 at 14 45 53" src="https://user-images.githubusercontent.com/2758453/105183207-33c36a00-5b2e-11eb-8b0b-41e99a17cd3f.png">

I installed the dracula theme on my tmux yesterday and showing the weather in Celcius is working. Can the issue be closed?

**Comment by ethancedwards8** [comment]
> <img alt="Screen Shot 2021-01-20 at 14 45 53" width="200" src="https://user-images.githubusercontent.com/2758453/105183207-33c36a00-5b2e-11eb-8b0b-41e99a17cd3f.png">
> 
> I installed the dracula theme on my tmux yesterday and showing the weather in Celcius is working. I added `set -g @dracula-show-fahrenheit false` in `.tmux.conf`.
> 
> Can the issue be closed?

I believe so, thanks.

**Comment by silndoj** [comment]
still doesnt work :(

**Comment by DavidCampbellTech** [comment]
yeah, doesn't work

**Comment by pkpg** [comment]
Can confirm it's not working

**Comment by pacifical** [comment]
it's working, but you should remove cached data from  
/tmp/.dracula-tmux-weather-data
/tmp/.dracula-tmux-weather-last-exec

and reinitialize tmux

**Comment by Theoreticallyhugo** [comment]
@pacifical (or anyone else) do you think we could/ should implement a snippet for detecting bad cached data to wipe it?

**Comment by pacifical** [comment]
@Theoreticallyhugo I'm not very familiar with plugin lifecycle since I only looked up the weather logic :) but my 2 cents - I agree, IMHO it would be okay to check/wipe whatever cached data we had on plugin startup to repopulate it (given it's time-sensitive data, like weather and such)
