### ISSUE TITLE
Bug: [gpu detection picks up non-gpu devices]

### ISSUE THREAD

**Issue by o0-o** [dracula/tmux#88]
`lspci -v | grep VGA` in the gpu script picks up devices classified as `Non-VGA`

```
❯ lspci -v | grep VGA
00:13.0 Non-VGA unclassified device: Intel Corporation 100 Series/C230 Series Chipset Family Integrated Sensor Hub (rev 31)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon Pro WX 5100] (prog-if 00 [VGA controller])
```

This results in `GPU unknown` in the status bar.

Not sure what the best solution here is. Maybe `grep 'VGA '`? Based on my system `grep 'VGA compatible controller'` would be the way to go, but I don't know if that's consistent across all hardware/linux.

**Comment by ethancedwards8** [comment]
What GPU do you have? Currently only NVIDIA gpu's are supported on Linux.

**Comment by ethancedwards8** [comment]
Closing due to no response and not being able to reproduce.

**Comment by georgmuntingh** [comment]
I had a similar issue in `gpu_usage.sh` and `gpu_ram_info.sh`, where lspci returned two lines with VGA compatible controllers. It grabbed the first, which was Intel, as opposed to the second, which was NVIDIA. I resolved this by changing line 12 in `gpu_usage.sh` and line 12 in `gpu_ram_info.sh` to:
`gpu=$(lspci -v | grep NVIDIA | grep VGA | head -n 1 | awk '{print $5}'`
