### ISSUE TITLE
Bug: [this doesn't work]

### ISSUE THREAD

**Issue by o0-o** [dracula/tmux#89]
`show_left_icon_padding` does nothing because this `seq` command fails in `dracula.sh`:

```
 padding="$(seq -f " " -s '' $show_left_icon_padding)"
```

A suitable alternative is:

```
padding="$(printf '%*s' $show_left_icon_padding)"
```

Tested in Arch Linux and macOS.

**Comment by ethancedwards8** [comment]
When I tested it out it was working on Arch, I just tried it out and it wasn't working on MacOS. Could be some differences between GNU seq and MacOS seq. Feel free to send a PR that fixes this, I'll test it out in both Arch and OSX if you do.

**Comment by manicmonkey** [comment]
Does not work for me either:

```
james@james-xps13:~$ seq -f " " -s '' 2
seq: format ‘ ’ has no % directive
james@james-xps13:~$ bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
james@james-xps13:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

The proposed change using `printf` works for me.

@ethancedwards8 are you saying you tried `printf` and it doesn't work on MacOS?

**Comment by ethancedwards8** [comment]
I meant the seq solution worked on MacOS, I didn't try the printf one. I just tested printf on MacOS and NixOS and it works. I can push push it to the repo or you can submit a PR @o0-o
